#!/bin/bash
shopt -s dotglob
for fn in $HOME/*; do
  if [ $fn = "$HOME/.vim" ] || [ $fn = "$HOME/.gitconfig" ]; then
    rm -rf $fn
  fi
done
cp -r $HOME/presets/.vim ~
exit1=$?
cp $HOME/presets/.gitconfig ~
exit2=$?
if [ $exit1 = '0' -a $exit2 = '0' ]; then
  echo 'config files succesfully replaced'
fi
