set nocompatible
filetype plugin on
let mapleader=' '
colorscheme industry

nnoremap <leader>w :w<cr>
nnoremap <leader>q :q!<cr>
nnoremap <leader>z :wq<cr>

inoremap {<CR> {<CR>}<esc>ko
inoremap {)<CR> {<CR>})<esc>ko
imap ,, <C-y>, 

cnoremap <expr> %% getcmdtype() == ':' ? expand('%:h').'/': '%%'

syntax on
set tabstop=2
set shiftwidth=2
set expandtab
set background=dark
set smartindent 
set autoindent
set showcmd
set incsearch
set visualbell
set laststatus=2
set noshowmode
set wildignore=/**/node_modules/**

" disable automatic comment insertion
au FileType * setlocal formatoptions-=c formatoptions-=r formatoptions-=o

autocmd FileType html setlocal commentstring=<!--\ %s\ -->
autocmd FileType handlebars setlocal commentstring={{!--\ %s\ --}}
autocmd FileType python setlocal commentstring=#\ %s

call plug#begin('~/.vim/plugged')

Plug 'tpope/vim-surround'
Plug 'tpope/vim-commentary'
Plug 'sheerun/vim-polyglot'
Plug 'itchyny/lightline.vim'
Plug 'vim-syntastic/syntastic'
Plug 'mattn/emmet-vim'

call plug#end()

"syntastic
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
" let g:syntastic_javascript_checkers = ['eslint']

" autocmd BufNewFile *.c 0r ~/.vim/templates/skeleton.c
" autocmd BufNewFile *.cpp 0r ~/.vim/templates/skeleton.cpp
" autocmd BufNewFile *.css 0r ~/.vim/templates/skeleton.css
" autocmd BufNewFile *.html 0r ~/.vim/templates/skeleton.html
" autocmd BufNewFile *.js 0r ~/.vim/templates/skeleton.js
